apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: cluster-nov-17
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    project: cluster-nov-17
    provider: eks
    region: us-east-1
  environments:
  - key: dev
    owner: olegy-ait
    repository: jx3-eks-asm
  - key: staging
  - key: production
  ingress:
    domain: 34.234.159.240.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: olegy-ait
  repository: nexus
  secretStorage: secretsManager
  vault: {}
  webhook: lighthouse
