# Source: kubernetes-external-secrets/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-external-secrets
  namespace: "secret-infra"
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::cluster-nov-17:role/cluster-nov-17-external-secrets-secrets-manager
    meta.helm.sh/release-name: 'kubernetes-external-secrets'
  labels:
    app.kubernetes.io/name: kubernetes-external-secrets
    helm.sh/chart: kubernetes-external-secrets-8.3.0
    app.kubernetes.io/instance: kubernetes-external-secrets
    app.kubernetes.io/managed-by: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
