filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-production
repositories:
- name: dev
  url: http://chartmuseum-jx.34.234.159.240.nip.io
releases:
- chart: dev/countryinfo-web
  version: 0.0.4
  name: countryinfo-web
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
